cookwithme/Models/Dish.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace cookwithme.Models
{
    public class Dish
    {
        public int ID { get; set; }
        public int CategoryID { get; set; }
        public string ApplicationUserID { get; set; }
        public string title { get; set; }
        public bool accepted { get; set; }
        public string ingredients { get; set; }
        public string description { get; set; }
        public DateTime created { get; set; }
        public Difficulty level { get; set; }
        //
        //
        public virtual DishPicture picture { get; set; }
        public virtual ApplicationUser user { get; set; }
        public virtual Category category { get; set; }
        public virtual ICollection<Comment> comments { get; set; }
        public virtual ICollection<Vote> votes { get; set; }
    }
    public enum Difficulty
    {
        [Display(Name="Bardzo łatwy")]
        Very_easy = 1,
        [Display(Name = "Łatwy")]
        Easy = 2,
        [Display(Name = "Średni")]
        Medium = 3,
        [Display(Name = "Trudny")]
        Hard = 4,
        [Display(Name = "Bardzo trudny")]
        Very_hard = 5,
    }
}

cookwithme/Models/DishViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace cookwithme.Models
{
    public class DishViewModelCreate
    {
        [Required]
        [Display(Name = "Nazwa")]
        public string Title { get; set; }

        [Display(Name = "Obrazek")]
        public string Picture { get; set; }

        [Required]
        [Display(Name = "Składniki")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Ingredients { get; set; }

        [Required]
        [Display(Name = "Opis")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Kategoria")]
        public int Category { get; set; }
    }
    public class DishViewModelEdit
    {
        [Required]
        [Display(Name = "Nazwa")]
        public string Title { get; set; }

        [Display(Name = "Obrazek")]
        public string Picture { get; set; }

        [Required]
        [Display(Name = "Składniki")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Ingredients { get; set; }

        [Required]
        [Display(Name = "Opis")]
        [AllowHtml]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required]
        [Display(Name = "Kategoria")]
        public int Category { get; set; }


        [Display(Name = "Opublikować?")]
        public bool Published { get; set; }

        public int HiddenID { get; set; }





    }
}

cookwithme/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cookwithme.DAL;
using cookwithme.Models;
using System.Runtime.Caching;
using System.Web.UI;

namespace cookwithme.Views
{
    public class CategoriesController : Controller
    {
        private KitchenContext db = new KitchenContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [OutputCache(Duration = 3600)]
        public ActionResult GetCategoriesThumbs()
        {
            var ExampleItems = new Dictionary<Category, Dish>();
            db.Categories.OrderBy(t => Guid.NewGuid()).ToList().ForEach(t => ExampleItems.Add(t, null));

            var dishes = db.Dishes.Where(t => t.accepted).OrderBy(t => Guid.NewGuid()).ToList();
            foreach (var item in dishes)
            {
                if (ExampleItems[item.category] == null)
                {
                    ExampleItems[item.category] = item;
                }
            }

            return View(ExampleItems);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            int NumberOfDishes = 0;
            var DataFromCache = MemoryCache.Default["NumberOfDishesForCategoryPage"];
            if (DataFromCache != null)
            {
                Int32.TryParse(DataFromCache.ToString(), out NumberOfDishes);
            }
            if (NumberOfDishes == 0)
            {
                MemoryCache.Default["NumberOfDishesForCategoryPage"] = db.Settings.Where(t => t.Type == "NumberOfDishesForCategoryPage").First().Value;
                Int32.TryParse((MemoryCache.Default["NumberOfDishesForCategoryPage"]).ToString(), out NumberOfDishes);
            }

            ViewBag.TotalPages = Math.Ceiling((double)(db.Dishes.Where(t => t.accepted && t.CategoryID == id)).Count() / (double)(NumberOfDishes));


            return View(category);

        }

        [HttpGet]
        [OutputCache(Duration = 3600)]
        public PartialViewResult CategoryList(int? category)
        {
            ViewBag.category = category == null ? 0 : category;
            return PartialView("Menu", db.Categories.ToList());
        }









        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cookwithme/Controllers/DishesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cookwithme.DAL;
using cookwithme.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.IO;
using System.Web.Helpers;
using System.Runtime.Caching;
using System.Web.UI;

namespace cookwithme.Controllers
{
    public class DishesController : Controller
    {
        private KitchenContext db = new KitchenContext();

        [HttpGet]
        public ActionResult Index()
        {

            int NumberOfDishes = 0;
            var DataFromCache = MemoryCache.Default["NumberOfDishesForPage"];
            if (DataFromCache != null)
            {
                Int32.TryParse(DataFromCache.ToString(), out NumberOfDishes);
            }
            if (NumberOfDishes == 0)
            {
                MemoryCache.Default["NumberOfDishesForPage"] = db.Settings.Where(t => t.Type == "NumberOfDishesForPage").First().Value;
                Int32.TryParse((MemoryCache.Default["NumberOfDishesForPage"]).ToString(), out NumberOfDishes);
            }

            ViewBag.TotalPages = Math.Ceiling((double)(db.Dishes.Where(t => t.accepted)).Count() / (double)(NumberOfDishes));

            return View();
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            if (dish == null || !dish.accepted)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ViewBag.VoteOfCurrentUser = db.Votes.Where(t => t.ApplicationUserID == currentUserId && t.DishID == id).FirstOrDefault();
            return View(dish);
        }

        [HttpGet]
        [OutputCache(Duration = 3600, Location = OutputCacheLocation.Server)]
        [AjaxOnly]
        public ActionResult GetDishesForPage(int? pageNumber)
        {
            int pageNumberForDB;
            if (!pageNumber.HasValue)
            {
                pageNumberForDB = 1;
            }
            else
            {
                pageNumberForDB = pageNumber.Value;
            }

            int ItemsForPage = 0;
            var DataFromCache = MemoryCache.Default["NumberOfDishesForPage"];
            if (DataFromCache != null)
            {
                Int32.TryParse(DataFromCache.ToString(), out ItemsForPage);
            }
            if (ItemsForPage == 0)
            {
                MemoryCache.Default["NumberOfDishesForPage"] = db.Settings.Where(t => t.Type == "NumberOfDishesForPage").First().Value;
                Int32.TryParse((MemoryCache.Default["NumberOfDishesForPage"]).ToString(), out ItemsForPage);
            }

            int SkippedItems = (pageNumberForDB - 1) * ItemsForPage;
            IQueryable<Dish> dishes = db.Dishes.Where(t => t.accepted).OrderBy(t => t.created).Skip(SkippedItems).Take(ItemsForPage);

            return PartialView(dishes.ToList());
        }

        [HttpGet]
        [AjaxOnly]
        [OutputCache(Duration = 3600, Location = OutputCacheLocation.Server)]
        public ActionResult GetCategoryDishesForPage(int categoryId, int? pageNumber)
        {
            int pageNumberForDB;
            if (!pageNumber.HasValue)
            {
                pageNumberForDB = 1;
            }
            else
            {
                pageNumberForDB = pageNumber.Value;
            }

            int ItemsForPage = 0;
            var DataFromCache = MemoryCache.Default["NumberOfDishesForCategoryPage"];
            if (DataFromCache != null)
            {
                Int32.TryParse(DataFromCache.ToString(), out ItemsForPage);
            }
            if (ItemsForPage == 0)
            {
                MemoryCache.Default["NumberOfDishesForCategoryPage"] = db.Settings.Where(t => t.Type == "NumberOfDishesForCategoryPage").First().Value;
                Int32.TryParse((MemoryCache.Default["NumberOfDishesForCategoryPage"]).ToString(), out ItemsForPage);
            }

            int SkippedItems = (pageNumberForDB - 1) * ItemsForPage;
            IQueryable<Dish> dishes = db.Dishes.Where(t => t.accepted && t.CategoryID == categoryId).OrderBy(t => t.created).Skip(SkippedItems).Take(ItemsForPage);

            return PartialView(dishes.ToList());
        }

        #region CREATE
        [HttpGet]
        [Authorize(Roles = "User")]
        public ActionResult Create()
        {
            var cats = db.Categories.ToList();
            ViewBag.Categories = cats;
            return View();
        }

        [Authorize(Roles = "User")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Title, Ingredients, Description, Category, Picture")] DishViewModelCreate dish)
        {
            string mime = "";
            byte[] picture = new byte[0];

            if (ModelState.IsValid)
            {
                HttpPostedFileBase file = Request.Files[0] == null ? null : Request.Files[0];
                if (file != null)
                {
                    mime = file.ContentType;
                    picture = new byte[file.ContentLength];
                    file.InputStream.Read(picture, 0, file.ContentLength);
                }
                var new_dish = new Dish
                {
                    ApplicationUserID = User.Identity.GetUserId(),
                    CategoryID = dish.Category,
                    created = DateTime.Now,
                    description = dish.Description,
                    ingredients = dish.Ingredients,
                    title = dish.Title,
                    accepted = false,
                };
                var new_picture = new DishPicture
                {
                    BigImage = picture,
                    BigMime = mime,
                };
                db.Dishes.Add(new_dish);
                db.SaveChanges();
                new_picture.ID = new_dish.ID;
                db.Pictures.Add(new_picture);
                db.SaveChanges();
                return RedirectToAction("Index", "Dishes");
            }
            else
            {
                var cats = db.Categories.ToList();
                ViewBag.Categories = cats;
                return View(dish);
            }
        }
        #endregion

        #region EDIT
        [HttpGet]
        [Authorize(Roles = "Moderator,Administrator")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dish dish = db.Dishes.Find(id);
            DishViewModelEdit model = new DishViewModelEdit
            {
                Title = dish.title,
                Category = dish.category.ID,
                Description = dish.description,
                Ingredients = dish.ingredients,
                HiddenID = dish.ID,
                Published = dish.accepted,
            };
            if (dish == null)
            {
                return HttpNotFound();
            }
            var cats = db.Categories.ToList();
            ViewBag.Categories = cats;
            ViewBag.SelectedCategory = dish.category.ID;
            return View(model);
        }
        [Authorize(Roles = "Moderator,Administrator")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Title, Ingredients, Description, Category, Difficulty, HiddenID, Published, Picture")] DishViewModelEdit model)
        {
            if (ModelState.IsValid)
            {
                Dish edited = new Dish
                {
                    ID = model.HiddenID,
                    title = model.Title,
                    ingredients = model.Ingredients,
                    description = model.Description,
                    CategoryID = model.Category,
                    accepted = model.Published,
                };

                string mime = "";
                byte[] picture = new byte[0];

                HttpPostedFileBase file = Request.Files[0] == null ? null : Request.Files[0];
                bool new_image = file.ContentLength != 0;

                DishPicture edited_picture = db.Pictures.First(t => t.ID == edited.ID);
                if (new_image)
                {
                    mime = file.ContentType;
                    picture = new byte[file.ContentLength];
                    file.InputStream.Read(picture, 0, file.ContentLength);

                    edited_picture.BigImage = picture;
                    edited_picture.BigMime = mime;
                }

                db.Dishes.Attach(edited);
                var entry = db.Entry(edited);
                entry.Property(t => t.title).IsModified = true;
                entry.Property(t => t.ingredients).IsModified = true;
                entry.Property(t => t.description).IsModified = true;
                entry.Property(t => t.CategoryID).IsModified = true;
                entry.Property(t => t.accepted).IsModified = true;
                db.SaveChanges();

                if (new_image)
                {
                    db.Pictures.Attach(edited_picture);
                    var entry2 = db.Entry(edited_picture);
                    entry2.Property(t => t.BigImage).IsModified = true;
                    entry2.Property(t => t.BigMime).IsModified = true;
                    db.SaveChanges();
                }
                return RedirectToAction("Manage", "Dishes");
            }
            return View(model);
        }
        #endregion

        #region MANAGE
        [HttpGet]
        [Authorize(Roles = "Moderator,Administrator")]
        public ActionResult Manage()
        {

cookwithme/Controllers/PartialsController.cs
using cookwithme.DAL;
using cookwithme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace cookwithme.Controllers
{
    public class PartialsController : Controller
    {
        private KitchenContext db = new KitchenContext();

        [HttpGet]
        public PartialViewResult StarsForComment(Comment comm)
        {
            var vote = db.Votes.FirstOrDefault(item => item.DishID == comm.DishID && comm.ApplicationUserID == item.ApplicationUserID);
            if (vote != null)
            {
                ViewBag.Filled = vote.ocena;
                ViewBag.Blank = 5 - ViewBag.Filled;
            }
            else
            {
                ViewBag.Filled = 0;
                ViewBag.Blank = 5;
            }
            return PartialView("Stars");
        }

        [HttpGet]
        public PartialViewResult StarsForDish(double average)
        {
            ViewBag.Title = average;
            ViewBag.Filled = (int)average;
            ViewBag.Blank = 5 - ViewBag.Filled;

            return PartialView("Stars");
        }

        [HttpGet]
        [OutputCache(Duration = 3600)]
        public PartialViewResult Carousel()
        {
            List<string> imagesUrls = new List<string>();
            db.Dishes.Where(t => t.accepted).OrderBy(t => Guid.NewGuid()).Take(3).ToList().ForEach(t => imagesUrls.Add(Url.Action("GetImage", "Dishes", new { t.ID })));

            return PartialView(imagesUrls);
        }

    }
}

cookwithme/Views/Dishes/Delete.cshtml
@model cookwithme.Models.Dish

@{
    ViewBag.Title = "Delete";
}
<div class="panel panel-default">
    <table class="table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nazwa</th>
                <th>Opublikowany</th>
                <th>Autor</th>
                <th>Data dodania</th>
                <th> </th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th>@Model.ID</th>
                <th>@Model.title</th>
                @if (Model.accepted)
                {
                    <th><span class="glyphicon glyphicon-plus success"></span></th>
                }
                else
                {
                    <th><span class="glyphicon glyphicon-minus success"></span></th>
                }
                <th>@Model.user.UserName</th>
                <th>@Model.created</th>
                <th></th>
            </tr>
        </tbody>
    </table>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-actions no-color">
        <p>Czy jesteś pewny, że chcesz usunąć tę potrawę?&nbsp;
        <input type="submit" value="Usuń" class="btn btn-danger" />
        &nbsp;lub&nbsp;@Html.ActionLink("wróć do listy potraw.", "Manage", "Dishes", new { @class="btn btn-default" })
        </p>
    </div>
}

cookwithme/Views/Dishes/Details.cshtml
@model cookwithme.Models.Dish
@using Microsoft.AspNet.Identity
@{
    ViewBag.Title = Model.title;
    var tmp = Url.Action("GetImage", "Dishes", new { Model.ID });
    var komentarze = Model.comments.OrderByDescending(t => t.added);

    bool IsLogged = User.Identity.IsAuthenticated;
}
<script type="text/javascript" src="~/Scripts/bootstrap-rating.js"></script>
<div class="row">
    <div class="col-md-3">
        <p class="lead">Kategorie</p>
        <div class="list-group">
            @Html.Action("CategoryList", "Categories", new { category = Model.CategoryID })
        </div>
    </div>
    <div class="col-md-9">

        <div class="thumbnail">
            <img class="img-responsive" src="@Url.Action("GetImage", "Dishes", new { Model.ID })" alt="">
            <div class="caption-full">
                @{
                    if (Model.votes.Count != 0)
                    {
                        var votesAverage = Model.votes.Average(t => t.ocena);
                        <div class="pull-right">
                            <span title="Średnia ocen: @votesAverage">@Html.Action("StarsForDish", "Partials", new { average = votesAverage })</span>
                        </div>
                    }
                }
                <h4>
                    @Model.title
                </h4>
                <hr class="divider">
                <div>
                    @Html.Raw(Model.ingredients)
                </div>
                <hr class="divider">
                <div>
                    @Html.Raw(Model.description)
                </div>
                <hr class="divider">
                <div class="ratings">
                    <div class="pull-right">@Model.comments.Count @Library.StrFunc.FormaSlowaKomentarze(Model.comments.Count)</div>
                    @if (IsLogged)
                    {
                        if (ViewBag.VoteOfCurrentUser != null)
                        {
                            <div id="votingLabel">Zmień głos: </div><div class="rating" id="rate1"></div>
                        }
                        else
                        {
                            <div id="votingLabel">Zagłosuj: </div><div class="rating" id="rate1"></div>
                        }
                    }
                </div>
            </div>
        </div>
        <div class="well" id="comments">
            <div class="row">
                <div class="text-right">
                    @if (IsLogged)
                    {
                        <div class="btn btn-default" style="margin-right:15px;" id="addcomment">Skomentuj</div>
                    }
                    else
                    {
                        @Html.ActionLink("Zaloguj się", "Login", "Account", new { returnURL = Request.Url.LocalPath + "#addcomment" }, new { @class = "btn btn-success", style = "margin-rigth:15px;" }) @:, żeby skomentować.
                }
                </div>
            </div>
            @if (IsLogged)
            {
                <div class="row" id="comment">
                    @using (Html.BeginForm("AddComment", "Dishes", FormMethod.Post, new { @class = "form-horizontal", role = "form", style = "margin-left:15px;" }))
                    {
                        @Html.AntiForgeryToken()
                        @Html.Hidden("path", Request.Url.LocalPath)
                        @Html.Hidden("id", Model.ID.ToString())
                        <div class="form-group">
                            <div class="col-md-12">
                                <textarea class="form-control" style="width:100%;" id="commentarea" name="comment_content"></textarea>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="submit" value="Wyślij" class="btn btn-success" />
                            </div>
                        </div>
                    }
                </div>
            }
            @foreach (var item in komentarze)
            {
                <hr />
                <div class="row">
                    <div class="col-md-12">
                        <div>
                            <span style="color:blue;">@item.user.UserName</span>
                            @Html.Action("StarsForComment", "Partials", new { comm = item })
                        </div>
                        @*@cookwithme.Controllers.PartialsController.User(item.ApplicationUserID)*@
                        <span class="pull-right" id="comment_time">@Library.DateTimeFunc.TimeElapsed(item.added)</span>
                        <p>@item.content</p>
                    </div>
                </div>
            }
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () { $("#comment").hide() });
    $("#addcomment").click(function () {
        $("#comment").toggle("fast", function () {
            $("#addcomment").text($("#comment").is(":visible") ? "Anuluj" : "Skomentuj");
            $("#comment").is(":visible") ? $("#commentarea").focus() : null;
        });
    });
</script>
<!-- you need to include the shieldui css and js assets in order for the charts to work -->
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/shieldui-all.min.css" />
<link rel="stylesheet" type="text/css" href="http://www.shieldui.com/shared/components/latest/css/light/all.min.css" />
<script type="text/javascript" src="http://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>
@{
    int currentVote = 0;
    if (ViewBag.VoteOfCurrentUser != null)
    {
        currentVote = (ViewBag.VoteOfCurrentUser as cookwithme.Models.Vote).ocena;
    }
}
<script type="text/javascript">
    initializeRatings();
    function initializeRatings() {
        $('#rate1').shieldRating({
            max: 5,
            step: 1,
            value: @currentVote,
            markPreset: false
        });
    }
</script>
<script type="text/javascript">
    $("#rate1").click(function () {
        $.ajax({
            url: '/Potrawy/@Model.ID/Ocen',
            contentType: 'application/json; charset=utf-8',
            type: 'POST',
            dataType: 'json',
            data: JSON.stringify({ vote: $('#rate1').swidget().value() }),
        });
        $('#votingLabel').html("Dziękujemy!");
        $(this).hide();
    });
</script>

cookwithme/Views/Dishes/GetCategoryDishesForPage.cshtml
@model IEnumerable<cookwithme.Models.Dish>
@using Library
@{
    var numberOfDishes = (Model as IList<cookwithme.Models.Dish>).Count;
    var currentDishInRow = 0;
    double votesAverage = 0;
}
@Html.Raw("<div class='row'>")
@foreach (var item in Model)
{
    if (currentDishInRow == 3)
    {
        currentDishInRow = 0;
        @Html.Raw("</div>")
        @Html.Raw("<div class='row'>")
    }
    currentDishInRow++;
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@Url.Action("GetThumb", "Dishes", new { item.ID })" alt="@item.title">
            <div class="caption">
                <h4>
                    <a href="#">@Html.ActionLink(item.title, "Details", new { id = item.ID })</a>
                </h4>
                <p>Opis</p>
            </div>
            <div class="ratings">
                <p class="pull-right">@item.comments.Count @StrFunc.FormaSlowaKomentarze(item.comments.Count)</p>
                <p>
                    @if (item.votes.Count != 0)
                    {
                        votesAverage = item.votes.Average(t => t.ocena);
                    }
                    else
                    {
                        votesAverage = 0;
                    }
                    @Html.Action("StarsForDish", "Partials", new { average = votesAverage })
                </p>
            </div>
        </div>
    </div>
}
@if (currentDishInRow != 0)
{
    @Html.Raw("</div>")
}

cookwithme/Views/Dishes/GetDishesForPage.cshtml
@model IEnumerable<cookwithme.Models.Dish>
@using Library
@{
    var numberOfDishes = (Model as IList<cookwithme.Models.Dish>).Count;
    var currentDishInRow = 0;
    double votesAverage = 0;
}
@Html.Raw("<div class='row'>")
@foreach (var item in Model)
{
    if (currentDishInRow == 3)
    {
        currentDishInRow = 0;
        @Html.Raw("</div>")
        @Html.Raw("<div class='row'>")
    }
    currentDishInRow++;
    <div class="col-sm-4 col-lg-4 col-md-4">
        <div class="thumbnail">
            <img src="@Url.Action("GetThumb", "Dishes", new { item.ID })" alt="@item.title">
            <div class="caption">
                <h4>
                    <a href="#">@Html.ActionLink(item.title, "Details", new { id = item.ID })</a>
                </h4>
                <p>@HttpUtility.HtmlDecode(StrFunc.RemoveHtmlTags(item.description).TruncateLongString(100))@Html.Raw("...")</p>
            </div>
            <div class="ratings">
                <p class="pull-right">@item.comments.Count @StrFunc.FormaSlowaKomentarze(item.comments.Count)</p>
                <p title="Ocena">
                    @if (item.votes.Count != 0)
                    {
                        votesAverage = item.votes.Average(t => t.ocena);
                    }
                    else
                    {
                        votesAverage = 0;
                    }
                    @Html.Action("StarsForDish", "Partials", new { average = votesAverage })
                </p>
            </div>
        </div>
    </div>
}
@if (currentDishInRow != 0)
{
    @Html.Raw("</div>")
}

cookwithme/Views/Dishes/GetFoundDishes.cshtml
@model IDictionary<cookwithme.Models.Dish, int>
@using Library

@if (Model.Count == 0)
{
    <h4>Niestety nie znaleziono potraw spełniających podane kryteria.</h4>
}
else
{
    <h4>Liczba znalezionych potraw: @Model.Count</h4>
}
@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-7">
            <a href="#">
                <img class="img-responsive" src="@Url.Action("GetThumb", "Dishes", new { item.Key.ID })" alt="@item.Key.title">
            </a>
        </div>
        <div class="col-md-5">
            <h3>@item.Key.title</h3>
            <p>@HttpUtility.HtmlDecode(StrFunc.RemoveHtmlTags(item.Key.description).TruncateLongString(1000))</p>
            <a class="btn btn-primary" href="@Url.Action("Details", "Dishes", new { id = item.Key.ID })">Szczegóły<span class="glyphicon glyphicon-chevron-right"></span></a>
        </div>
    </div>
    <hr />
}

cookwithme/Views/Dishes/Index.cshtml
@{
    ViewBag.Title = "Strona Główna";
}
<div class="row">
    <div class="col-md-3">
        <p class="lead">Kategorie</p>
        <div class="list-group">
            @Html.Action("CategoryList", "Categories", null)
        </div>
    </div>
    <div class="col-md-9">
        @Html.Action("Carousel", "Partials")
        <div class="center-block" id="loader" title="Trwa wczytywanie..."><img src="~/Images/ajax-loader.gif"/></div>
        <!--PLACE TO DISPLAY DISHES-->
        <div id="Potrawy">

        </div>
        <nav>
            <ul class="pager">
                <li><a href="javascript:;" id="prevPage">Poprzednia</a></li>
                <li><a href="javascript:;" id="nextPage">Następna</a></li>
            </ul>
        </nav>

    </div>

</div>
<script type="text/javascript">
    var currentPage = 1;
    var maxPage = @ViewBag.TotalPages
    $.ajax({
        url: '/Potrawy/Strony/1',
        contentType: 'application/html; charset=utf-8',
        type: 'GET',
        dataType: 'html'
    })
    .success(function (result) {
        $('#loader').hide();
        $('#Potrawy').html(result);
    });
    $("#nextPage").click(function () {
        if (currentPage < maxPage) {
            currentPage++;
            $.ajax({
                url: '/Potrawy/Strony/' + currentPage,
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                dataType: 'html'
            })
            .success(function (result) {
                $('#Potrawy').html(result)
            })
        }
    });
    $("#prevPage").click(function () {
        if (currentPage > 1) {
            currentPage--;

            $.ajax({
                url: '/Potrawy/Strony/' + currentPage,
                contentType: 'application/html; charset=utf-8',
                type: 'GET',
                dataType: 'html'
            })
            .success(function (result) {
                $('#Potrawy').html(result)
            })
        }

    });
    var $loading = $('#loader');
    $(document)
      .ajaxStart(function () {
          $loading.show();
          $("#Potrawy").html("");
      })
      .ajaxStop(function () {
          $loading.hide();
      });
</script>