cookwithme/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cookwithme.DAL;
using cookwithme.Models;
using System.Runtime.Caching;
using System.Web.UI;

namespace cookwithme.Views
{
    public class CategoriesController : Controller
    {
        private KitchenContext db = new KitchenContext();

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        [OutputCache(Duration = 3600)]
        public ActionResult GetCategoriesThumbs()
        {
            var ExampleItems = new Dictionary<Category, Dish>();
            db.Categories.OrderBy(t => Guid.NewGuid()).ToList().ForEach(t => ExampleItems.Add(t, null));

            var dishes = db.Dishes.Where(t => t.accepted).OrderBy(t => Guid.NewGuid()).ToList();
            foreach (var item in dishes)
            {
                if (ExampleItems[item.category] == null)
                {
                    ExampleItems[item.category] = item;
                }
            }

            return View(ExampleItems);
        }

        [HttpGet]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Category category = db.Categories.Find(id);
            if (category == null)
            {
                return HttpNotFound();
            }

            int NumberOfDishes = 0;
            var DataFromCache = MemoryCache.Default["NumberOfDishesForCategoryPage"];
            if (DataFromCache != null)
            {
                Int32.TryParse(DataFromCache.ToString(), out NumberOfDishes);
            }
            if (NumberOfDishes == 0)
            {
                MemoryCache.Default["NumberOfDishesForCategoryPage"] = db.Settings.Where(t => t.Type == "NumberOfDishesForCategoryPage").First().Value;
                Int32.TryParse((MemoryCache.Default["NumberOfDishesForCategoryPage"]).ToString(), out NumberOfDishes);
            }

            ViewBag.TotalPages = Math.Ceiling((double)(db.Dishes.Where(t => t.accepted && t.CategoryID == id)).Count() / (double)(NumberOfDishes));


            return View(category);

        }

        [HttpGet]
        [OutputCache(Duration = 3600)]
        public PartialViewResult CategoryList(int? category)
        {
            ViewBag.category = category == null ? 0 : category;
            return PartialView("Menu", db.Categories.ToList());
        }









        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

cookwithme/Controllers/StatisticsController.cs
using cookwithme.DAL;
using cookwithme.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;

namespace cookwithme.Controllers
{
    public class StatisticsController : Controller
    {
        private KitchenContext db = new KitchenContext();
        
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [OutputCache(Duration = 3600)]
        public PartialViewResult BestRated()
        {
            List<Dish> ListOfDishes = db.Dishes.ToList();
            Dictionary<Dish, double> AveragesOfDishes = new Dictionary<Dish,double>();
            ListOfDishes.ForEach(t => AveragesOfDishes.Add(t, t.votes.Count != 0 ? t.votes.Average(s => s.ocena) : 0));

            return PartialView(AveragesOfDishes.OrderByDescending(t => t.Value).Take(10));
        }

        [OutputCache(Duration = 3600)]
        public PartialViewResult MostCommented()
        {
            List<Dish> ListOfDishes = db.Dishes.ToList();
            Dictionary<Dish, int> CommentsOfDishes = new Dictionary<Dish, int>();
            ListOfDishes.ForEach(t => CommentsOfDishes.Add(t, t.comments.Count));

            return PartialView(CommentsOfDishes.OrderByDescending(t => t.Value).Take(10));
        }

        [OutputCache(Duration = 3600)]
        public PartialViewResult BestAddingDishes()
        {
            List<ApplicationUser> ListOfUsers = db.Users.ToList();
            Dictionary<ApplicationUser, int> AddedDishesOfUser = new Dictionary<ApplicationUser, int>();
            ListOfUsers.ForEach(t => AddedDishesOfUser.Add(t, t.dishes.Count));

            return PartialView(AddedDishesOfUser.OrderByDescending(t => t.Value).Take(10));
        }

        [OutputCache(Duration = 3600)]
        public PartialViewResult BestCommentator()
        {
            List<ApplicationUser> ListOfUsers = db.Users.ToList();
            Dictionary<ApplicationUser, int> AddedCommentsOfUser = new Dictionary<ApplicationUser, int>();
            ListOfUsers.ForEach(t => AddedCommentsOfUser.Add(t, t.comments.Count));

            return PartialView(AddedCommentsOfUser.OrderByDescending(t => t.Value).Take(10));
        }
    }
}

cookwithme/Views/Shared/_Layout.cshtml
@{
    bool isUser = User.IsInRole("User");
    bool isModerator = User.IsInRole("Moderator");
    bool isAdministrator = User.IsInRole("Administrator");
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cook With Me! - @ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/bootstrap.css" rel="stylesheet">
    <link href="~/Content/shop-homepage.css" rel="stylesheet">
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">

        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="icon-bar">as</span>
                    <span class="icon-bar">sd</span>
                    <span class="icon-bar">asd</span>
                </button>
                @Html.ActionLink("CookWithMe", "Index", "Dishes", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Kategorie", "Index", "Categories")</li>
                    <li>@Html.ActionLink("Wyszukaj", "Search", "Dishes")</li>
                    <li>@Html.ActionLink("Statystyki", "Index", "Statistics")</li>
                    @if (isUser)
                    {
                        <li>@Html.ActionLink("Dodaj", "Create", "Dishes")</li>
                    }
                    @if (isModerator)
                    {
                        <li>@Html.ActionLink("Zarządzaj", "Manage", "Dishes")</li>
                    }
                    @if (isAdministrator)
                    {
                        <li>@Html.ActionLink("Użytkownicy", "Manage", "Account")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    <div class="container">

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright © 2014 mrleon. All rights reserved.</p>
                </div>
            </div>
        </footer>

    </div>
    @*<script src="~/Scripts/jquery-1.10.2.js"></script>*@

    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.min.js"></script>
    
    @RenderSection("scripts", required: false)

</body>
</html>